include:
  - test-app-docker-compose.yaml
  - docker-compose-minimal.yaml
  services:
  otel-collector:
  volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock  # <- this is required
    command: [ "--config=/etc/otel-collector-config.yaml" ]